version: "3"

services:
  app:
    build: ./.docker/app/
    # entrypoint: dockerize -template ./.docker/app/.env.app.default:.env -wait tcp://db:3306 -timeout 30s ./.docker/app/entrypoint.sh
    container_name: app
    volumes:
      - .:/var/www
    # env_file:
    #   - ./.docker/app/.env.docker-compose
    depends_on:
      - db
      - redis
    networks:
      - app-net

  nginx:
    build: .docker/nginx
    container_name: nginx
    working_dir: /var/www
    entrypoint: dockerize -template .docker/nginx/nginx.template:/etc/nginx/conf.d/nginx.conf -timeout 100s .docker/nginx/entrypoint.sh
    environment:
      - PORT=9000
      - HOST=app
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-net

  db:
    build: ./.docker/mysql/
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    # volumes:
    #   - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - app-net

  redis:
    image: redis:alpine
    expose:
      - 6379
    container_name: redis
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
